cc_binary(
    name = "simple_window",
    srcs = ["simple_window.cpp"],
    deps = [
        "//game:game",
        "//error_reporter:error_reporter",
        "//tests:rectangle",
        "@sdl2//:sdl2",
    ],
    visibility = ["//visibility:public"]
)
